### ISSUE TITLE
Use with React 16 Portals seems to cause reconciliation to rebuild all components on every change.

### ISSUE THREAD

**Issue by Ross-Esmond** [davidtheclark/react-displace#7]
React-displace with portals is causing reconciliation to always register the entire tree below displace to be entirely new components and reinstantiates the classes.

I have yet to figure out exactly why this is happening, but if I remove my dependency on react-displace and use portals directly reconciliation works.

I'm looking further into the problem now.

**Comment by davidtheclark** [comment]
Hi @Ross-Esmond.

When Portals are enabled, I *think* this library is using Portals exactly [as prescribed by the React docs](https://reactjs.org/docs/portals.html): https://github.com/davidtheclark/react-displace/blob/85a7833c28af37659ec4222218c80e15b157c8cd/src/displace.js#L78-L87

Also, I'm not reproducing this behavior in some apps I have that are using this library (via [react-aria-modal](https://github.com/davidtheclark/react-aria-modal)) in combination with React 16.

So I suspect that there isn't a problem with this library, but maybe with the particular situation you're working with. Please re-open if it can be reliably demonstrated in a reduced test case.

**Comment by Ross-Esmond** [comment]
I'll have to reproduce the issue in a repo. It showed up through react-aria-modal when using the renderTo option. Which is interesting; looking at displace's code, that shouldn't make a difference.
